export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const CERRAR_SESION = 'CERRAR_SESION';

export const LISTAR_USUARIOS = 'LISTAR_USUARIOS';
export const MODIFICAR_USUARIO = 'MODIFICAR_USUARIO';
export const ELIMINAR_USUARIO = 'ELIMINAR_USUARIO';
export const AGREGAR_USUARIO = 'AGREGAR_USUARIO';

export const LISTAR_PLATOS = 'LISTAR_PLATOS';
export const MODIFICAR_PLATO = 'MODIFICAR_PLATO';
export const ELIMINAR_PLATO = 'ELIMINAR_PLATO';
export const AGREGAR_PLATO = 'AGREGAR_PLATO';

export const LISTAR_MESAS = 'LISTAR_MESAS';
export const MODIFICAR_MESA = 'MODIFICAR_MESA';
export const ELIMINAR_MESA = 'ELIMINAR_MESA';
export const AGREGAR_MESA = 'AGREGAR_MESA';

export const LISTAR_SUGERENCIAS = 'LISTAR_SUGERENCIAS';
export const MODIFICAR_SUGERENCIA = 'MODIFICAR_SUGERENCIA';
export const ELIMINAR_SUGERENCIA = 'ELIMINAR_SUGERENCIA';
export const AGREGAR_SUGERENCIA = 'AGREGAR_SUGERENCIA';
